### ISSUE TITLE
How did you decrypt skillfiles

### ISSUE THREAD

**Issue by masakitenchi** [lonqie/SchaleDB#10]
I'm currently trying to decrypt the whole database from scratch, but when it comes to skill level files, I found that the data seems to be encrypted. For example, trying to decode all the .bytes file using base64 would only give me a pile of nonsense string. Would you like to give me some hint about how you decrypted all those files and build your own database?

BTW, there are some other files are compressed & encrypted with password, and one of the .zip file is the compressed version of LevelSkill. I wonder if there's anything different between them.

**Comment by lonqie** [comment]
Please don't open issues for questions such as this, Schale DB isn't a data extraction/data mining project for the game, so this isn't the place for it. The issues section is for bug reports/feature requests for the Schale DB website.

I'm afraid I don't have an answer for your question, because I don't do any extraction/decryption on the game's data, nor do I know how to. However, feel free to drop me a message on Discord, and I'll see if there is anything I can help with.
