### ISSUE TITLE
Hieronymus skill data not same in game

### ISSUE THREAD

**Issue by uchisl** [lonqie/SchaleDB#2]
in hardcore  green light decreases Hieronymus's damage resistance by 55%  
![57ABC26D54B9523976DF7BC29482A20B](https://user-images.githubusercontent.com/106339966/173778906-659a8ce0-c5b6-4246-beaa-7ca066035488.png)

**Comment by lonqie** [comment]
I understand where the confusion is coming from, the skill description is
technically correct by game logic, as it refers to the reduction in the
damage resistance value (DamagedRatio) rather than the overall % increase
in damage taken. However, I will change this to make it more clear and also
state the increase in damage taken.

To explain, Hieronymus starts with a DamagedRatio of 16000 (-60% damage
taken) and the green relic reduces this value by 2200 per stack. This
effectively equals a 55% increase to incoming damage each time, which
matches the in-game tooltip.
The effect is identical across all difficulties, including Insane.

**Comment by uchisl** [comment]
understand，thanks for explain

**Comment by lonqie** [comment]
Fixed in 75cdf989c907767d88122e2ed475716c4812cf1e.
