### ISSUE TITLE
List stages where the item drops from an Item Box

### ISSUE THREAD

**Issue by edwardez** [lonqie/SchaleDB#8]
HI,

Thanks for making SchaleDB! It's very helpful.

As we know, in game each mission only tells you it will drop from 3 kinds of blueprints, however actually some missions may drop additional items, this is known as "subdrop".  For example, the game tells you `Knitted Wool Hat Blueprint` drops from 4-1~4-5 Normal, however this item actually drops from 10 Series Nomal missions as well, as shown in SchaleDB.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/11089470/184511036-8bfcc79c-dd63-418e-90da-4e471b257df6.png">

However, it seems like SchaleDB won't tell you in the reverse way, meaning on the "what missions drop this item" page, 10-x Normal missions are not there.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/11089470/184511074-2580ecb3-d2f2-46da-9045-ab7e850c3730.png">

To be more specific I think it would be better if we can see something like this

<img width="611" alt="image" src="https://user-images.githubusercontent.com/11089470/184511155-11833115-c03d-4458-8f94-fdb47cf08e07.png">

I also checked [Trello](https://trello.com/b/7FnXxi05/schaledb-development) but seems like this is not mentioned there. I am wondering is this intended or is this something not implemeted yet? Thanks!

**Comment by lonqie** [comment]
Thanks for raising this. Yes, the stages where the item is from an "item box" type of drop aren't shown in that list currently.
I like the mockup UI but I would probably hide the chance % label since that is the drop rate of the box (which contains one item from it at random) and not that specific item, and maybe show "Item Box" or something similar.

**Comment by edwardez** [comment]
Hi, 
> since that is the drop rate of the box (which contains one item from it at random) and not that specific item, and maybe show "Item Box" or something similar.

Do you know if this is completely random or is it something measureable?

<img width="358" alt="image" src="https://user-images.githubusercontent.com/11089470/184517213-7ade2536-94db-4e89-9652-3caae59f6892.png">

For exmaple, I can see here there is a chance of 22.5% to get this T1/T2 item box. Does this mean 11.25% chance I will get a T1 hat and 11.25% chance I will get a T2 one? If so is it better if we display the actual probability, or would you prefer completely hide the probability if the item comes from a item box?

**Comment by lonqie** [comment]
For the Equipment boxes I believe it's actually 2/3 and 1/3 chance to get the higher/lower tier. Might be fine to show the chance e.g. "7.5% (Item Box)" actually as that is the chance you will drop that specific item from the stage.

Really the drop list as shown above should also be reworked to show each possible item in the box, rather than just listing them all in the tooltip like it does currently. Gets a bit complicated though since the drop rate of the box still needs to be shown, showing just the calculated drop rate of each item in a list could be misleading since you can only drop one or the other. Will experiment with how to display this nicely.

**Comment by edwardez** [comment]
I see, thanks for the explanation!

**Comment by lonqie** [comment]
First part of this has been addressed with 8d27760c2a310552a19eab428a89a3a275b00920 - the stages now show as a possible drop location. I've added the rates to the tooltip on item boxes for now but will look into improving the UI for these in the future.
